name: Check Melon Tickets

on:
  schedule:
    - cron: "*/1 * * * *"  # 1분마다 실행
  workflow_dispatch:      # 수동 실행 버튼 활성화

jobs:
  check_tickets:
    runs-on: ubuntu-latest

    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 204755
          schedule-id: 100001
          seat-id: 1_0
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '잔여석 떴다!'